export const default1 = [
  {
    name: "check stock market",
    id: Math.random(),
    priority: "high",
    status: false,
  },
  {
    name: "eat first meal",
    id: Math.random(),
    priority: "high",
    status: false,
  },
  {
    name: "eat second meal",
    id: Math.random(),
    priority: "high",
    status: false,
  },
  {
    name: "go outside",
    id: Math.random(),
    priority: "high",
    status: false,
  },
  {
    name: "code",
    id: Math.random(),
    priority: "high",
    status: false,
  },
  {
    name: "exercise",
    id: Math.random(),
    priority: "high",
    status: false,
  },
  {
    name: "talk to Vivien",
    id: Math.random(),
    priority: "high",
    status: false,
  },
  {
    name: "genshin: daily events",
    id: Math.random(),
    priority: "high",
    status: false,
  },
  {
    name: "genshin: daily comissions",
    id: Math.random(),
    priority: "high",
    status: false,
  },
  {
    name: "genshin: use overnight resin",
    id: Math.random(),
    priority: "high",
    status: false,
  },
  {
    name: "genshin: use resin from the day",
    id: Math.random(),
    priority: "high",
    status: false,
  },
  {
    name: "juggle",
    id: Math.random(),
    priority: "normal",
    status: false,
  },
  {
    name: "yoyo",
    id: Math.random(),
    priority: "normal",
    status: false,
  },

  {
    name: "genshin: daily artifacts",
    id: Math.random(),
    priority: "normal",
    status: false,
  },
  {
    name: "genshin: daily crystal ores",
    id: Math.random(),
    priority: "normal",
    status: false,
  },
  {
    name: "genshin: random events",
    id: Math.random(),
    priority: "low",
    status: false,
  },
  {
    name: "play ssbm",
    id: Math.random(),
    priority: "low",
    status: false,
  },
  {
    name: "play tetris",
    id: Math.random(),
    priority: "low",
    status: false,
  },
];
